spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${POSTGRES_CONNECTION_URL:jdbc:postgresql://localhost/station}
    username: ${POSTGRES_USERNAME:station_sa}
    password: ${POSTGRES_PASSWORD:password}
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:/liquibase/main.xml
logging:
  level:
    root: INFO
    org.disturbednny: DEBUG